name: Update README

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 PM (noon)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        run: node update_readme.js

      - name: Commit changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
        run: |
          git config --global user.email "${GH_EMAIL}"
          git config --global user.name "${GH_NAME}"
          git add .
          git commit -m "Update README"
          git push https://x-access-token:${GH_PAT}@github.com/pythonicboat/pythonicboat.git
